"""
Django settings for FashioHub project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file() -> None:
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return

    try:
        for raw_line in env_path.read_text(encoding='utf-8').splitlines():
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value
    except Exception:
        pass


def _env_bool(name: str, default: bool = False) -> bool:
    value = str(os.getenv(name, str(default))).strip().lower()
    return value in ('1', 'true', 't', 'yes', 'y', 'on')


def _env_int(name: str, default: int) -> int:
    try:
        return int(str(os.getenv(name, default)).strip())
    except (TypeError, ValueError):
        return default


_load_env_file()
RUNNING_TESTS = 'test' in sys.argv

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'dev-only-change-this-secret-key-before-production-use-9482f17a3b6c'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False. It used to default to True, so a deploy that simply had no
# DEBUG variable set served Django's debug pages on the live domain - the 404
# page listed every admin-panel URL, and any unhandled exception would have
# exposed the traceback along with settings. Developers opt in with DEBUG=1 in
# their local .env; forgetting to set it can now only make a machine safer.
DEBUG = _env_bool('DEBUG', False)

ALLOWED_HOSTS = [
    host.strip() for host in os.getenv(
        'ALLOWED_HOSTS',
        'vibemall.in,www.vibemall.in,vibemall.cloud,www.vibemall.cloud,localhost,127.0.0.1,187.124.98.177'
    ).split(',') if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'https://vibemall.in,https://www.vibemall.in,https://vibemall.cloud,https://www.vibemall.cloud'
    ).split(',') if origin.strip()
]

IS_PRODUCTION = (not DEBUG) and (not RUNNING_TESTS)
COMING_SOON_MODE = _env_bool('COMING_SOON_MODE', True)
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', IS_PRODUCTION)
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', IS_PRODUCTION)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', IS_PRODUCTION)
SECURE_HSTS_SECONDS = _env_int('SECURE_HSTS_SECONDS', 31536000 if IS_PRODUCTION else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', IS_PRODUCTION)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', IS_PRODUCTION)
SECURE_REFERRER_POLICY = os.getenv('SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    # 'livereload',  # Commented out - not needed
    'Hub',
    'trading',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Above ComingSoonModeMiddleware on purpose. Responses travel back up the
    # list, so a middleware that short-circuits during its request phase is
    # only seen by the ones above it — with this below, the coming-soon
    # redirect went out with no X-Frame-Options at all.
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Hub.middleware.ComingSoonModeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'Hub.middleware.BlockedUserMiddleware',
    'Hub.middleware.ResellLinkMiddleware',
    'Hub.rate_limiter.check_rate_limit_middleware',
]

ROOT_URLCONF = 'VibeMall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Hub' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Hub.context_processors.cart_wishlist_context',
                'Hub.context_processors.site_settings_context',
                'Hub.context_processors.header_menu_context',
                'Hub.context_processors.reseller_access_context',
                'Hub.context_processors.admin_panel_context',
                'Hub.context_processors.mobile_review_prompt_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'VibeMall.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'CONN_MAX_AGE': 0,  # Don't persist connections
        # The PRAGMAs that make this survivable with several writers are applied
        # in Hub.db_pragmas, not here: `init_command` and `transaction_mode`
        # need Django 5.1+, and this project runs 4.2 locally against 5.2 on the
        # server. A connection_created hook works on both.
        'OPTIONS': {
            'timeout': 30,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = _env_int('EMAIL_PORT', 587)
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = _env_bool('EMAIL_USE_SSL', False)
EMAIL_TIMEOUT = _env_int('EMAIL_TIMEOUT', 20)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').strip()
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'VibeMall <info.vibemall@gmail.com>').strip()
SERVER_EMAIL = os.getenv('SERVER_EMAIL', EMAIL_HOST_USER or 'info.vibemall@gmail.com').strip()
SITE_URL = os.getenv('SITE_URL', 'https://vibemall.in').rstrip('/')

# Admin Notification Settings
ADMIN_NOTIFICATION_EMAILS = [
    email.strip() 
    for email in os.getenv('ADMIN_NOTIFICATION_EMAILS', '').split(',') 
    if email.strip()
]
ENABLE_ADMIN_ORDER_NOTIFICATIONS = _env_bool('ENABLE_ADMIN_ORDER_NOTIFICATIONS', True)


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.getenv('STATIC_ROOT', str(BASE_DIR / 'staticfiles')))
PROJECT_STATIC_DIR = BASE_DIR / 'static'
HUB_STATIC_DIR = BASE_DIR / 'Hub' / 'static'

# Collect static files from both project root and Hub app
STATICFILES_DIRS = [
    dir for dir in [PROJECT_STATIC_DIR, HUB_STATIC_DIR] 
    if dir.exists()
]

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media')))
PRODUCT_IMAGE_ROOT = os.getenv(
    'PRODUCT_IMAGE_ROOT',
    r'D:\VibeMallProduct\ProductImage' if os.name == 'nt' else str(MEDIA_ROOT / 'product_images')
)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File upload settings for multiple images
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB per file
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB total POST data
FILE_UPLOAD_MAX_NUMBER_FILES = 20  # Maximum 20 files per upload

# Razorpay Payment Gateway Settings
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '').strip()
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '').strip()
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET', '').strip()
RAZORPAY_UPI_DEBUG = os.getenv('RAZORPAY_UPI_DEBUG', False) == 'True'

# Razorpay Webhook Configuration (Construct from domain)
def _build_webhook_url():
    webhook_url = os.getenv('RAZORPAY_WEBHOOK_URL', '').strip()
    if webhook_url:
        return webhook_url
    
    # Auto-construct from ALLOWED_HOSTS
    for host in ALLOWED_HOSTS:
        if 'vibemall.in' in host or 'vibemall.cloud' in host:
            protocol = 'https' if IS_PRODUCTION else 'http'
            return f'{protocol}://{host}/api/razorpay-webhook/'
    
    # Fallback
    return f"https://vibemall.in/api/razorpay-webhook/"

RAZORPAY_WEBHOOK_URL = _build_webhook_url()

# UPI Verification Settings
UPI_TEST_MODE = os.getenv('UPI_TEST_MODE', 'False' if IS_PRODUCTION else 'True') == 'True'
UPI_PROVIDER_VALIDATION = _env_bool('UPI_PROVIDER_VALIDATION', True)
UPI_AUTO_REFUND_ENABLED = _env_bool('UPI_AUTO_REFUND_ENABLED', True)

# Direct Bank Transfer Settings
BANK_TRANSFER_ENABLED = _env_bool('BANK_TRANSFER_ENABLED', True)
BANK_VERIFICATION_AUTO_APPROVE = _env_bool('BANK_VERIFICATION_AUTO_APPROVE', False)
BANK_VERIFICATION_TIMEOUT_HOURS = _env_int('BANK_VERIFICATION_TIMEOUT_HOURS', 24)

# Verification Webhook Logging
WEBHOOK_LOG_ENABLED = _env_bool('WEBHOOK_LOG_ENABLED', True)
WEBHOOK_LOG_RETENTION_DAYS = _env_int('WEBHOOK_LOG_RETENTION_DAYS', 30)
WEBHOOK_LOG_LEVEL = os.getenv('WEBHOOK_LOG_LEVEL', 'INFO')

# ── n8n AI Automation ──────────────────────────────────────────────────────
# Secret key for authenticating n8n product ingestion requests.
# n8n HTTP Request node must send: Authorization: Bearer <N8N_API_KEY>
N8N_API_KEY = os.getenv('N8N_API_KEY', '').strip()
# ───────────────────────────────────────────────────────────────────────────

# ── Telegram → AI Product Automation ───────────────────────────────────────
# Products sent to the Telegram bot are staged as ProductDraft rows, enriched
# by Claude, and published only after an admin selects a Category and approves.
#
# Run these two processes alongside the web server:
#   python manage.py telegram_product_bot        (message intake)
#   python manage.py process_product_drafts      (AI + image pipeline)

# Bot token from @BotFather. Keep it in .env — never commit it.
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '').strip()

# Optional allow-list of chat/channel IDs the bot will accept products from.
# Empty means "every chat the bot can see" — set this in production.
TELEGRAM_ALLOWED_CHAT_IDS = [
    chat.strip() for chat in os.getenv('TELEGRAM_ALLOWED_CHAT_IDS', '').split(',') if chat.strip()
]

# Where the Bot API update offset is persisted between restarts.
TELEGRAM_OFFSET_FILE = os.getenv('TELEGRAM_OFFSET_FILE', str(BASE_DIR / 'logs' / 'telegram_offset.json'))

# Which AI provider enriches drafts: 'auto', 'ollama', 'claude', 'gemini' or
# 'groq'. 'auto' prefers a reachable Ollama server, then Claude, then Gemini,
# then Groq.
AUTOMATION_AI_PROVIDER = os.getenv('AUTOMATION_AI_PROVIDER', 'ollama').strip().lower()

# ── Ollama (local models — no API key, no quota, no per-token cost) ────────
# Point this at any machine running `ollama serve`; it does not have to be
# this server. A GPU box on the LAN will be far faster than CPU inference.
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://127.0.0.1:11434').strip()
AUTOMATION_OLLAMA_MODEL = os.getenv('AUTOMATION_OLLAMA_MODEL', 'qwen3:8b').strip()

# Local generation is slow — an 8B model on CPU can take minutes for a long
# structured response, so this is a ceiling rather than an expectation.
AUTOMATION_OLLAMA_TIMEOUT = _env_int('AUTOMATION_OLLAMA_TIMEOUT', 900)
AUTOMATION_OLLAMA_CONTEXT = _env_int('AUTOMATION_OLLAMA_CONTEXT', 8192)

# Vision is detected from the model's own metadata. Set this only to override
# that — e.g. force it off while testing a multimodal model.
_ollama_vision = os.getenv('AUTOMATION_OLLAMA_VISION', '').strip()
AUTOMATION_OLLAMA_VISION = (
    None if not _ollama_vision else _ollama_vision.lower() in ('1', 'true', 'yes', 'on')
)
# ───────────────────────────────────────────────────────────────────────────

# Google Gemini — has a FREE tier with vision and needs no credit card.
# Create a key at https://aistudio.google.com/apikey
GEMINI_API_KEY = (os.getenv('GEMINI_API_KEY', '') or os.getenv('GOOGLE_API_KEY', '')).strip()
# Left empty on purpose so the client's own DEFAULT_MODEL applies. This used to
# default to 'gemini-flash-latest', which always won because the setting was
# never unset - so gemini.py's carefully chosen free-tier default was dead code
# and every request went to a full-size Flash alias. Those are the ones that
# 429 almost immediately on the free tier, which is what "Gemini only gives a
# few tries" actually was. Measured on this project's own prompt:
# gemini-3.1-flash-lite answers in 0.76s, gemini-flash-latest in 2.80s.
AUTOMATION_GEMINI_MODEL = os.getenv('AUTOMATION_GEMINI_MODEL', '').strip()

# Vision cost controls. Gemini's free tier limits *input tokens per minute*,
# and images dominate that budget, so keep batches small on a free key.
AUTOMATION_VISION_MAX_IMAGES = _env_int('AUTOMATION_VISION_MAX_IMAGES', 8)
AUTOMATION_VISION_MAX_EDGE = _env_int('AUTOMATION_VISION_MAX_EDGE', 768)

# Groq — free tier, no credit card, text only (no vision model available on
# the free tier at the time this was written). Create a key at
# https://console.groq.com/keys
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '').strip()
# Left empty on purpose, same reasoning as AUTOMATION_GEMINI_MODEL above — an
# unset env var must resolve to groq.py's own DEFAULT_MODEL, not the empty
# string winning over it.
AUTOMATION_GROQ_MODEL = os.getenv('AUTOMATION_GROQ_MODEL', '').strip()
# Deliberately NOT AUTOMATION_AI_MAX_TOKENS (Claude/Gemini's shared 8000
# default) — Groq's strict-mode models cap at 6-8K tokens *per minute*,
# counted against the completion budget requested rather than what comes
# back, so reusing 8000 here exhausts the whole window on one request before
# a single prompt token is counted. 0 means unset, so groq.py's own
# DEFAULT_MAX_TOKENS applies.
AUTOMATION_GROQ_MAX_TOKENS = _env_int('AUTOMATION_GROQ_MAX_TOKENS', 0)

# Anthropic credentials for extraction, copywriting and image analysis.
# Without any key the pipeline still runs, using rule-based extraction only.
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '').strip()
AUTOMATION_AI_MODEL = os.getenv('AUTOMATION_AI_MODEL', 'claude-opus-5').strip()
AUTOMATION_AI_MAX_TOKENS = _env_int('AUTOMATION_AI_MAX_TOKENS', 8000)
# low | medium | high | xhigh | max — 'medium' balances cost against quality
# for catalogue extraction. Raise it if descriptions need more polish.
AUTOMATION_AI_EFFORT = os.getenv('AUTOMATION_AI_EFFORT', 'medium').strip()

# Telegram albums arrive as several updates; wait this long after the last one
# before parsing, so a multi-photo post is treated as a single product.
AUTOMATION_ALBUM_SETTLE_SECONDS = _env_int('AUTOMATION_ALBUM_SETTLE_SECONDS', 10)

# Retry budget per draft before it is marked FAILED.
AUTOMATION_MAX_ATTEMPTS = _env_int('AUTOMATION_MAX_ATTEMPTS', 4)

# Guard rails on inbound media.
AUTOMATION_MAX_IMAGE_BYTES = _env_int('AUTOMATION_MAX_IMAGE_BYTES', 12 * 1024 * 1024)
AUTOMATION_MAX_IMAGES_PER_DRAFT = _env_int('AUTOMATION_MAX_IMAGES_PER_DRAFT', 40)
AUTOMATION_MAX_VIDEOS_PER_DRAFT = _env_int('AUTOMATION_MAX_VIDEOS_PER_DRAFT', 5)
# Telegram's Bot API refuses downloads above 20 MB, so a larger value here
# would only produce failures further along.
AUTOMATION_MAX_VIDEO_BYTES = _env_int('AUTOMATION_MAX_VIDEO_BYTES', 20 * 1024 * 1024)

# A single unlabelled price in a supplier message is the supplier's own price,
# i.e. the MRP / original price - not what the store sells at. With this on,
# that value fills `old_price` and the selling price is left for the admin to
# set at approval. Turn it off to treat a lone price as the selling price.
AUTOMATION_SUPPLIER_PRICE_IS_MRP = _env_bool('AUTOMATION_SUPPLIER_PRICE_IS_MRP', True)

# Height of the catalogue-code strip Meesho prints below a product photo. The
# Meesho/Market toggle on the review screen applies this to every image at
# once; detection is only used to tell the admin a strip is there.
AUTOMATION_MEESHO_CROP_PX = _env_int('AUTOMATION_MEESHO_CROP_PX', 28)

# How long a draft with photos and a description waits for a rate sent as its
# own follow-up message, before the worker treats it as complete.
AUTOMATION_PRICE_WINDOW_SECONDS = _env_int('AUTOMATION_PRICE_WINDOW_SECONDS', 45)

# A rate sent as its own message is the supplier quoting their price, so it is
# recorded as this shop's COST and the margin is added on top. Set false to
# treat it as the selling price instead.
AUTOMATION_SEPARATE_PRICE_IS_COST = _env_bool('AUTOMATION_SEPARATE_PRICE_IS_COST', True)

# Stock a product is published with when the supplier message states none.
# Publishing at zero would put it straight into "out of stock".
AUTOMATION_DEFAULT_STOCK = _env_int('AUTOMATION_DEFAULT_STOCK', 50)

# Most of one item a single order may contain, enforced on add-to-cart, cart
# updates and Buy Now. Stock still wins when it is the smaller number.
MAX_QUANTITY_PER_ITEM = _env_int('MAX_QUANTITY_PER_ITEM', 2)

# Videos sent to the bot become Reels linked to the product on approval.
AUTOMATION_CREATE_REELS = _env_bool('AUTOMATION_CREATE_REELS', True)
# ───────────────────────────────────────────────────────────────────────────

# ── Message grouping (chat sources) ────────────────────────────────────────
# Telegram only sets media_group_id for a true album. Suppliers often send
# photos one at a time, so messages from the same chat are also grouped by
# time: a new message joins the draft in progress for this many seconds.
AUTOMATION_GROUP_WINDOW_SECONDS = _env_int('AUTOMATION_GROUP_WINDOW_SECONDS', 180)

# How long a chat draft must be idle before the worker processes it — i.e.
# how long to assume the supplier is still sending. Longer than the album
# settle window, because a person is slower than a single album upload.
AUTOMATION_GROUP_QUIET_SECONDS = _env_int('AUTOMATION_GROUP_QUIET_SECONDS', 45)
# ───────────────────────────────────────────────────────────────────────────
