# Auto-generated admin registrations
# Generated by AdminCodeGenerator

class BackupConfigurationAdmin(admin.ModelAdmin):
    list_display = ['id', 'regular_folder_name', 'special_folder_name', 'send_success_email', 'send_failure_email', 'is_active', 'created_at']

admin.site.register(BackupConfiguration, BackupConfigurationAdmin)

class BackupLogAdmin(admin.ModelAdmin):
    list_display = ['id', 'email_sent', 'status', 'created_at', 'updated_at']

admin.site.register(BackupLog, BackupLogAdmin)

class TeraboxSettingsAdmin(admin.ModelAdmin):
    list_display = ['id', 'connection_status_message', 'created_at', 'updated_at', 'folder_root_path', 'auto_create_folders', 'is_connected']

admin.site.register(TeraboxSettings, TeraboxSettingsAdmin)

class BackupCleanupRequestAdmin(admin.ModelAdmin):
    list_display = ['id', 'email_sent', 'status', 'folder_path', 'folder_label', 'requested_at', 'confirmed_at']

admin.site.register(BackupCleanupRequest, BackupCleanupRequestAdmin)
