# Generated by Django 6.0.1 on 2026-02-05 21:24
#
# NOTE:
# ChatThread/ChatMessage were introduced on another migration branch
# (`0029_chatmessage_alter_adminemailsettings_admin_email_and_more`).
# Keeping create-model operations here causes duplicate-table errors on
# fresh databases. This migration is intentionally a no-op.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0040_alter_adminemailsettings_admin_email_mainpageproduct'),
    ]

    operations = []
