# Generated by Django 6.0.1 on 2026-02-05 21:59
#
# NOTE:
# ChatAttachment and ChatMessage(message blank=True) are already handled in
# `0029_chatmessage_alter_adminemailsettings_admin_email_and_more`.
# Keeping those operations here causes duplicate-table errors on fresh
# databases. This migration is intentionally a no-op.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0041_chatthread_chatmessage'),
    ]

    operations = []
