# Generated by Django 6.0.1 on 2026-02-08 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0048_wallet_balance_and_refund_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approval_status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'R-Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto Approved')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('RECEIVED', 'Received'), ('UNABLE_TO_REACH', 'Unable to Reach'), ('RESCHEDULED', 'Rescheduled'), ('QC_PENDING', 'Waiting for Product Review'), ('REFUND_PENDING', 'Waiting for Refunded'), ('WRONG_RETURN', 'Wrong Return'), ('REFUNDED', 'Refunded'), ('REPLACED', 'Replaced'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('QC_PASSED', 'QC Passed'), ('QC_FAILED', 'QC Failed')], default='REQUESTED', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('refund_method', models.CharField(blank=True, choices=[('WALLET', 'VibeMall Wallet'), ('BANK', 'Direct Bank Transfer'), ('RAZORPAY', 'RazorPay')], max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=34)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=200)),
                ('upi_name', models.CharField(blank=True, max_length=200)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_request', to='Hub.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_cancellations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Cancellation Request',
                'verbose_name_plural': 'Order Cancellation Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
