# Generated by Django 6.0.1 on 2026-02-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0049_alter_order_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='margin_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
