# Generated by Django 5.2.9 on 2026-02-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0029_chatmessage_alter_adminemailsettings_admin_email_and_more'),
        ('Hub', '0051_categoryicon_icon_size'),
    ]

    operations = [
    ]
