# Generated by Django 5.2.9 on 2026-02-22 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0055_subcategory_icon_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Reel title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Reel description')),
                ('video_file', models.FileField(blank=True, help_text='Generated video file', null=True, upload_to='reels/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Video thumbnail', null=True, upload_to='reels/thumbnails/')),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('duration_per_image', models.IntegerField(default=3, help_text='Seconds per image')),
                ('transition_type', models.CharField(default='fade', help_text='Transition effect', max_length=20)),
                ('background_music', models.FileField(blank=True, help_text='Background music (optional)', null=True, upload_to='reels/music/')),
                ('is_published', models.BooleanField(default=False, help_text='Publish on website')),
                ('is_processing', models.BooleanField(default=False, help_text='Video generation in progress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reel',
                'verbose_name_plural': 'Reels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for reel', upload_to='reels/images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('text_overlay', models.CharField(blank=True, help_text='Text to display on this image', max_length=200)),
                ('text_position', models.CharField(default='center', help_text='Text position (center, top, bottom)', max_length=20)),
                ('text_color', models.CharField(default='white', help_text='Text color', max_length=20)),
                ('text_size', models.IntegerField(default=70, help_text='Text font size')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Hub.reel')),
            ],
            options={
                'verbose_name': 'Reel Image',
                'verbose_name_plural': 'Reel Images',
                'ordering': ['order'],
            },
        ),
    ]
