# Generated by Django 5.2.9 on 2026-02-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0056_reel_reelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='add_end_screen',
            field=models.BooleanField(default=True, help_text='Add branded end screen with logo'),
        ),
        migrations.AddField(
            model_name='reel',
            name='end_screen_duration',
            field=models.IntegerField(default=3, help_text='End screen duration in seconds'),
        ),
        migrations.AddField(
            model_name='reel',
            name='watermark_logo',
            field=models.ImageField(blank=True, help_text='Watermark logo (transparent PNG)', null=True, upload_to='reels/logos/'),
        ),
        migrations.AddField(
            model_name='reel',
            name='watermark_opacity',
            field=models.FloatField(default=0.7, help_text='Watermark opacity (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='reel',
            name='watermark_position',
            field=models.CharField(choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], default='top-right', help_text='Watermark position', max_length=20),
        ),
        migrations.AlterField(
            model_name='reel',
            name='transition_type',
            field=models.CharField(choices=[('fade', 'Fade'), ('zoom', 'Zoom In'), ('slide', 'Slide'), ('none', 'None')], default='zoom', help_text='Transition effect', max_length=20),
        ),
    ]
