# Generated by Django 5.2.9 on 2026-02-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0057_reel_add_end_screen_reel_end_screen_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=True, help_text='Can this product be returned?'),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_methods',
            field=models.CharField(default='COD,ONLINE,UPI,CARD', help_text='Comma-separated: COD,ONLINE,UPI,CARD', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='return_days',
            field=models.PositiveIntegerField(default=7, help_text='Return period in days'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.TextField(blank=True, help_text='Return policy details'),
        ),
    ]
