# Generated by Django 5.2.9 on 2026-02-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0058_product_is_returnable_product_payment_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='product',
            field=models.ForeignKey(
                blank=True,
                help_text='Linked product for watch-and-shop redirect',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='watch_shop_reels',
                to='Hub.product',
            ),
        ),
    ]
