# Generated by Django 5.2.9 on 2026-02-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0059_reel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='like_count',
            field=models.PositiveIntegerField(default=0, help_text='Total reel likes'),
        ),
        migrations.AddField(
            model_name='reel',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Total reel views'),
        ),
    ]
