# Generated by Django 5.2.9 on 2026-02-22 18:17

from django.db import migrations, models


def backfill_reel_metrics(apps, schema_editor):
    Reel = apps.get_model('Hub', 'Reel')
    Reel.objects.filter(view_count=0).update(view_count=25)
    Reel.objects.filter(like_count=0).update(like_count=3)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0060_reel_like_count_reel_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='like_count',
            field=models.PositiveIntegerField(default=3, help_text='Total reel likes'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='view_count',
            field=models.PositiveIntegerField(default=25, help_text='Total reel views'),
        ),
        migrations.RunPython(backfill_reel_metrics, noop_reverse),
    ]
