# Generated by Django 5.2.9 on 2026-02-23 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0061_alter_reel_like_count_alter_reel_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Coupon code (e.g., FIRST15)', max_length=50, unique=True)),
                ('coupon_type', models.CharField(choices=[('MANUAL', 'Manual Code'), ('FIRST_ORDER', 'First Order (15%)'), ('SPEND_5K', 'Spend 5000 (15%)')], default='MANUAL', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description shown to users')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed amount', max_digits=10)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart value', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount cap', max_digits=10, null=True)),
                ('usage_limit', models.IntegerField(blank=True, help_text='Total usage limit (null = unlimited)', null=True)),
                ('usage_per_user', models.IntegerField(default=1, help_text='Usage limit per user')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount from coupon', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Applied coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hub.coupon'),
        ),
        migrations.CreateModel(
            name='UserSpendTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Total lifetime spending', max_digits=12)),
                ('current_cycle_spent', models.DecimalField(decimal_places=2, default=0, help_text='Spending in current 5K cycle', max_digits=12)),
                ('last_5k_coupon_at', models.DateTimeField(blank=True, help_text='When last 5K coupon was earned', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spend_tracker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Spend Tracker',
                'verbose_name_plural': 'User Spend Trackers',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hub.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hub.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'ordering': ['-used_at'],
                'unique_together': {('coupon', 'order')},
            },
        ),
    ]
