# Generated by Django 5.2.9 on 2026-02-23 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0062_coupon_order_coupon_discount_order_coupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyShipStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional custom title. Leave blank to use product name.', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional custom image. Leave blank to use product image.', null=True, upload_to='ready_ship_styles/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_ship_styles', to='Hub.product')),
            ],
            options={
                'verbose_name': 'Ready-to-Ship Style',
                'verbose_name_plural': 'Ready-to-Ship Styles',
                'ordering': ['order', 'id'],
            },
        ),
    ]
