# Generated by Django 5.2.9 on 2026-02-23 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0063_readyshipstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Coupon code (e.g., FIRST5)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('MANUAL', 'Manual Code'), ('FIRST_ORDER', 'First Order (5%)'), ('SPEND_5K', 'Spend 5000 (5%)')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='MainPageSubCategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title shown over image. Leave blank to use sub-category name.', max_length=200)),
                ('image', models.ImageField(upload_to='main_page_subcategory_banners/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower appears first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_page_banners', to='Hub.subcategory')),
            ],
            options={
                'verbose_name': 'Main Page Sub-category Banner',
                'verbose_name_plural': 'Main Page Sub-category Banners',
                'ordering': ['order', 'id'],
            },
        ),
    ]
