# Generated by Django 5.2.9 on 2026-02-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0065_categoryicon_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_page', models.CharField(blank=True, max_length=120)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
