# Generated by Django 5.2.9 on 2026-02-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0066_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readyshipstyle',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional custom image. Recommended sizes: Hero (first item): 2100x900px (21:9), Cards: 1600x900px (16:9). Leave blank to use product image.', null=True, upload_to='ready_ship_styles/'),
        ),
    ]
