# Generated by Django 5.2.9 on 2026-02-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0067_update_readyship_image_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, help_text='External product link (e.g., Meesho URL) - for admin reference only', max_length=500),
        ),
        migrations.AlterField(
            model_name='mainpagesubcategorybanner',
            name='image',
            field=models.ImageField(help_text='Recommended size: 800 x 600 px (4:3 ratio) for best display', upload_to='main_page_subcategory_banners/'),
        ),
    ]
