# Generated by Django 5.2.9 on 2026-02-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0068_product_product_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base amount before margin', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='reseller',
            field=models.ForeignKey(blank=True, help_text='Reseller user for resell orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resold_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='total_margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total margin amount for reseller', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original product price before margin', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='resell_from_name',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Use reseller field instead', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='resell_from_phone',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Use reseller.phone instead', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='margin_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reseller margin per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, help_text='Price shown to customer (includes margin for resell orders)', max_digits=10),
        ),
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('WALLET', 'Wallet')], max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Transaction',
                'verbose_name_plural': 'Payout Transactions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reseller_enabled', models.BooleanField(default=False)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseller Profile',
                'verbose_name_plural': 'Reseller Profiles',
            },
        ),
        migrations.CreateModel(
            name='ResellLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resell_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('margin_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resell_links', to='Hub.product')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resell_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resell Link',
                'verbose_name_plural': 'Resell Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_earning', to='Hub.order')),
                ('payout_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hub.payouttransaction')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_earnings', to=settings.AUTH_USER_MODEL)),
                ('resell_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hub.reselllink')),
            ],
            options={
                'verbose_name': 'Reseller Earning',
                'verbose_name_plural': 'Reseller Earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='resell_link',
            field=models.ForeignKey(blank=True, help_text='Resell link used for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hub.reselllink'),
        ),
        migrations.AddIndex(
            model_name='payouttransaction',
            index=models.Index(fields=['reseller', 'status'], name='Hub_payoutt_reselle_474cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='payouttransaction',
            index=models.Index(fields=['status'], name='Hub_payoutt_status_fb39ab_idx'),
        ),
        migrations.AddIndex(
            model_name='reselllink',
            index=models.Index(fields=['resell_code'], name='Hub_reselll_resell__6435f0_idx'),
        ),
        migrations.AddIndex(
            model_name='reselllink',
            index=models.Index(fields=['reseller', 'is_active'], name='Hub_reselll_reselle_d16d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerearning',
            index=models.Index(fields=['reseller', 'status'], name='Hub_reselle_reselle_419c36_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerearning',
            index=models.Index(fields=['status'], name='Hub_reselle_status_1bdc45_idx'),
        ),
    ]
