# Generated by Django 5.2.9 on 2026-02-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0069_order_base_amount_order_reseller_order_total_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('PRICE_DROP', 'Price Drop Alert'), ('STOCK_AVAILABLE', 'Stock Available'), ('RETURN_APPROVED', 'Return Approved'), ('REFUND_PROCESSED', 'Refund Processed'), ('POINTS_EARNED', 'Loyalty Points Earned'), ('SPECIAL_OFFER', 'Special Offer'), ('EARNING_CONFIRMED', 'Reseller Earning Confirmed'), ('PAYOUT_COMPLETED', 'Payout Completed'), ('PAYOUT_FAILED', 'Payout Failed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('NEW_RESELL_ORDER', 'New Resell Order')], max_length=30),
        ),
    ]
