# Generated by Django 5.2.9 on 2026-03-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0070_add_resell_notification_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_area', models.CharField(choices=[('first', 'First Banner Area'), ('second', 'Second Banner Area')], default='first', help_text='Select which banner area this belongs to', max_length=20)),
                ('badge_text', models.CharField(blank=True, help_text="Text above the title (e.g., 'Bestseller Products', 'Featured Products')", max_length=100)),
                ('title', models.CharField(help_text="Main banner title/heading (e.g., 'PC & Docking Station')", max_length=200)),
                ('description', models.CharField(blank=True, help_text="Banner description/subtitle (e.g., 'Discount 20% Off, Top Quality Products')", max_length=300)),
                ('image', models.ImageField(help_text='Banner background image. Recommended size: 600 x 400 px', upload_to='main_page_banners/')),
                ('link_url', models.CharField(default='#', help_text='URL to redirect when banner is clicked (e.g., /shop?category=electronics)', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first in each area). Only 2 banners per area are recommended.')),
                ('is_active', models.BooleanField(default=True, help_text='Activate/Deactivate this banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Main Page Banner',
                'verbose_name_plural': 'Main Page Banners',
                'ordering': ['banner_area', 'order', 'id'],
                'indexes': [models.Index(fields=['banner_area', 'is_active', 'order'], name='Hub_mainpag_banner__0e0426_idx')],
            },
        ),
    ]
