# Generated by Django 5.2.9 on 2026-03-02 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0071_mainpagebanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every 15 Days'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom Dates')], default='MONTHLY', help_text='How often should backups run?', max_length=20)),
                ('backup_root_path', models.CharField(default='D:\\VibeMallBackUp', help_text='Local root folder for all backups', max_length=500)),
                ('regular_folder_name', models.CharField(default='RegularBackUp', help_text='Subfolder name for automated regular backups', max_length=100)),
                ('special_folder_name', models.CharField(default='SpecialBackup', help_text='Subfolder name for manual special backups and ITR reports', max_length=100)),
                ('schedule_time', models.TimeField(default='03:00', help_text='What time should the backup run? (HH:MM in 24-hour format)')),
                ('schedule_weekday', models.IntegerField(blank=True, default=0, help_text='Day of week for weekly backups (0=Monday, 6=Sunday)', null=True)),
                ('custom_dates', models.CharField(default='1,7,15,30', help_text='Comma-separated dates for custom backups (e.g., 1,7,15,30)', max_length=50)),
                ('enable_terabox_backup', models.BooleanField(default=False, help_text='Deprecated: Terabox backup is disabled in local backup mode')),
                ('terabox_auto_folder_create', models.BooleanField(default=True, help_text='Automatically create dated folders in Terabox (01, 07, 15, 30)?')),
                ('notification_emails', models.TextField(blank=True, default='', help_text='Comma-separated email addresses for backup notifications')),
                ('send_success_email', models.BooleanField(default=True, help_text='Send email when backup completes successfully?')),
                ('send_failure_email', models.BooleanField(default=True, help_text='Send email when backup fails?')),
                ('keep_local_backups_days', models.IntegerField(default=30, help_text='Keep local backups for how many days?')),
                ('keep_cloud_backups_days', models.IntegerField(default=365, help_text='Keep cloud backups for how many days?')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable automatic backups?')),
                ('last_backup_at', models.DateTimeField(blank=True, help_text='Timestamp of last completed backup', null=True)),
                ('next_backup_at', models.DateTimeField(blank=True, help_text='Calculated timestamp of next scheduled backup', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configurations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TeraboxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_access_token', models.TextField(blank=True, help_text='Terabox API access token (keep confidential!)')),
                ('refresh_token', models.TextField(blank=True, help_text='Terabox refresh token for token renewal')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When does the current token expire?', null=True)),
                ('folder_root_path', models.CharField(default='/VibeMall_Backups', help_text='Root folder path in Terabox for backups', max_length=500)),
                ('auto_create_folders', models.BooleanField(default=True, help_text='Automatically create dated folders (01, 07, 15, 30)?')),
                ('is_connected', models.BooleanField(default=False, help_text='Is Terabox account successfully connected?')),
                ('connection_status_message', models.CharField(blank=True, help_text='Last connection status message', max_length=255)),
                ('last_sync_time', models.DateTimeField(blank=True, help_text='Last successful sync/upload to Terabox', null=True)),
                ('total_backups_synced', models.IntegerField(default=0, help_text='Total number of backups uploaded to Terabox')),
                ('cloud_storage_used_mb', models.DecimalField(decimal_places=2, default=0, help_text='Approximate storage used in Terabox (MB)', max_digits=12)),
                ('account_info', models.TextField(blank=True, help_text='Terabox account info (JSON - email, display_name, etc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terabox Settings',
                'verbose_name_plural': 'Terabox Settings',
            },
        ),
        migrations.AlterField(
            model_name='mainpagebanner',
            name='banner_area',
            field=models.CharField(choices=[('first', 'Promotion area 3 card'), ('second', 'Marketing area 2 card')], default='first', help_text='Select which banner area this belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='mainpagebanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first in each area). Promotion area: 3 banners, Marketing area: 2 banners.'),
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('MANUAL', 'Manual Trigger'), ('SCHEDULED', 'Scheduled'), ('ON_DEMAND', 'On Demand'), ('SPECIAL', 'Special Backup'), ('ITR_REPORT', 'ITR Financial Report')], default='SCHEDULED', max_length=20)),
                ('backup_scope', models.CharField(choices=[('REGULAR', 'Regular Backup'), ('SPECIAL', 'Special Backup'), ('ITR', 'ITR Report Backup')], default='REGULAR', help_text='Regular, special, or ITR report backup', max_length=20)),
                ('backup_frequency', models.CharField(blank=True, help_text='Which schedule triggered this backup?', max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='PENDING', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('users_count', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('payments_count', models.IntegerField(default=0)),
                ('products_count', models.IntegerField(default=0)),
                ('returns_count', models.IntegerField(default=0)),
                ('transactions_count', models.IntegerField(default=0)),
                ('local_file_path', models.CharField(blank=True, help_text='Path to local backup file', max_length=500)),
                ('monthly_folder_label', models.CharField(blank=True, help_text='Monthly folder label (e.g., 2026-03)', max_length=20)),
                ('terabox_file_path', models.CharField(blank=True, help_text='Deprecated cloud backup path', max_length=500)),
                ('file_size_mb', models.DecimalField(decimal_places=2, default=0, help_text='Size of backup file in MB', max_digits=10)),
                ('terabox_synced', models.BooleanField(default=False, help_text='Deprecated cloud sync flag')),
                ('requires_cleanup_confirmation', models.BooleanField(default=False, help_text='Whether this backup generated an old-data cleanup confirmation request')),
                ('email_sent', models.BooleanField(default=False, help_text='Was notification email sent?')),
                ('error_message', models.TextField(blank=True, help_text='Error details if backup failed')),
                ('error_trace', models.TextField(blank=True, help_text='Full error traceback for debugging')),
                ('backup_data_types', models.CharField(default='users,orders,payments,products,returns,transactions', help_text='Comma-separated list of data types in this backup', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Admin notes for this backup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Log',
                'verbose_name_plural': 'Backup Logs',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['status'], name='Hub_backupl_status_2a969b_idx'), models.Index(fields=['start_time'], name='Hub_backupl_start_t_728b48_idx'), models.Index(fields=['backup_type', 'status'], name='Hub_backupl_backup__08ae3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BackupCleanupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(max_length=500)),
                ('folder_label', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('backup_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_requests', to='Hub.backuplog')),
            ],
            options={
                'verbose_name': 'Backup Cleanup Request',
                'verbose_name_plural': 'Backup Cleanup Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
