# Generated by Django 5.2.9 on 2026-03-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0035_new_features_models'),
        ('Hub', '0072_backupconfiguration_teraboxsettings_and_more'),
    ]

    operations = [
    ]
