# Generated by Django 5.2.9 on 2026-03-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0075_birthdayanniversaryreminder_blogcategory_blogcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureActivationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=200)),
                ('url_name', models.CharField(max_length=100)),
                ('url_pattern', models.CharField(max_length=200)),
                ('view_name', models.CharField(max_length=100)),
                ('template_path', models.CharField(max_length=200)),
                ('url_exists', models.BooleanField(default=False)),
                ('view_exists', models.BooleanField(default=False)),
                ('template_exists', models.BooleanField(default=False)),
                ('loads_successfully', models.BooleanField(default=False)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('last_tested', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Activation Status',
                'verbose_name_plural': 'Feature Activation Statuses',
                'ordering': ['feature_name'],
            },
        ),
        migrations.CreateModel(
            name='MigrationExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('migration_file', models.CharField(max_length=200)),
                ('execution_order', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Migration Execution Log',
                'verbose_name_plural': 'Migration Execution Logs',
                'ordering': ['execution_order', 'executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelActivationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('model_file', models.CharField(max_length=200)),
                ('has_migration', models.BooleanField(default=False)),
                ('migration_applied', models.BooleanField(default=False)),
                ('table_created', models.BooleanField(default=False)),
                ('admin_registered', models.BooleanField(default=False)),
                ('admin_verified', models.BooleanField(default=False)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Model Activation Status',
                'verbose_name_plural': 'Model Activation Statuses',
                'ordering': ['model_name'],
            },
        ),
    ]
