# Generated by Django 5.2.9 on 2026-03-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0076_featureactivationstatus_migrationexecutionlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='adminuserrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='adminuserrole',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='adminuserrole',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='bulkproductimport',
            name='imported_by',
        ),
        migrations.RemoveField(
            model_name='discountcoupon',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.RemoveField(
            model_name='lowstockalert',
            name='acknowledged_by',
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='AdminRole',
        ),
        migrations.DeleteModel(
            name='AdminUserRole',
        ),
        migrations.DeleteModel(
            name='BulkProductImport',
        ),
        migrations.DeleteModel(
            name='DiscountCoupon',
        ),
        migrations.DeleteModel(
            name='LowStockAlert',
        ),
    ]
