# Generated by Django 5.2.9 on 2026-03-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0078_adminrole_emailtemplate_adminuserrole_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reel',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Reel', 'verbose_name_plural': 'Reels'},
        ),
        migrations.AddField(
            model_name='reel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order on homepage (lower numbers appear first)'),
        ),
    ]
