# Generated by Django 5.2.9 on 2026-03-26 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0079_alter_reel_options_reel_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RTOCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DELIVERY_FAILED', 'Delivery Failed'), ('RTO_INITIATED', 'RTO Initiated'), ('RTO_IN_TRANSIT', 'RTO In Transit'), ('RTO_RECEIVED', 'RTO Received'), ('RTO_CLOSED', 'RTO Closed')], default='DELIVERY_FAILED', max_length=20)),
                ('reason', models.CharField(choices=[('WRONG_ADDRESS', 'Wrong Address'), ('CUSTOMER_UNAVAILABLE', 'Customer Unavailable'), ('CUSTOMER_REFUSED', 'Customer Refused Delivery'), ('FAKE_ORDER', 'Fake / High-Risk Order'), ('COURIER_ISSUE', 'Courier Issue'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('reason_notes', models.TextField(blank=True)),
                ('resolution_action', models.CharField(blank=True, choices=[('RESTOCK', 'Restock'), ('HOLD', 'Hold for Review'), ('REPACK', 'Repack and Reship'), ('DISPOSE', 'Dispose / Damaged'), ('VENDOR_RETURN', 'Return to Vendor')], max_length=20)),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rto_case', to='Hub.order')),
            ],
            options={
                'verbose_name': 'RTO Case',
                'verbose_name_plural': 'RTO Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RTOHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rto_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Hub.rtocase')),
            ],
            options={
                'verbose_name_plural': 'RTO Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
