# Generated by Django 5.2.9 on 2026-04-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0081_update_contact_email_default_and_existing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, help_text='Color variant for this image', max_length=100),
        ),
    ]
