# Generated by Django 5.2.9 on 2026-04-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0082_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_points_awarded',
            field=models.BooleanField(default=False, help_text='Whether delivery bonus loyalty points were awarded'),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='points_available',
            field=models.IntegerField(default=0, help_text='Available points = total_points - points_used'),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='points_used',
            field=models.IntegerField(default=0, help_text='Total points redeemed'),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='total_points',
            field=models.IntegerField(default=0, help_text='Total points earned (NEVER decrements)'),
        ),
    ]
