# Generated by Django 5.2.9 on 2026-04-06 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0083_order_delivery_points_awarded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='Bank account number (masked)', max_length=50)),
                ('ifsc', models.CharField(help_text='IFSC code', max_length=11)),
                ('account_name', models.CharField(blank=True, help_text='Account holder name from bank', max_length=255)),
                ('razorpay_contact_id', models.CharField(blank=True, help_text='Razorpay Contact ID', max_length=100)),
                ('razorpay_fund_account_id', models.CharField(blank=True, help_text='Razorpay Fund Account ID', max_length=100)),
                ('razorpay_payout_id', models.CharField(blank=True, help_text='Razorpay Payout ID for verification', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFYING', 'Verifying'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_error', models.TextField(blank=True, help_text='Error message if verification failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UPIVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(help_text='UPI ID (e.g., name@bank)', max_length=255)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay Payment ID for ₹1 verification', max_length=100)),
                ('razorpay_order_id', models.CharField(blank=True, help_text='Razorpay Order ID for ₹1 verification', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WAITING_PAYMENT', 'Waiting for Payment'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_error', models.TextField(blank=True, help_text='Error message if verification failed')),
                ('refund_attempted', models.BooleanField(default=False, help_text='Whether ₹1 refund was attempted after verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upi_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(help_text='Razorpay Payment ID to refund', max_length=100)),
                ('razorpay_refund_id', models.CharField(blank=True, help_text='Razorpay Refund ID', max_length=100)),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount refunded in ₹', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reason', models.TextField(help_text='Reason for refund')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='Hub.order')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order', 'razorpay_refund_id')},
            },
        ),
    ]
