# Generated by Django 5.2.9 on 2026-04-06 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0084_bankverification_upiverification_refund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('upi', 'UPI Verification'), ('bank', 'Bank Verification'), ('both', 'Both')], max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=255)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('test_amount', models.CharField(default='100', max_length=20)),
                ('test_status', models.CharField(blank=True, max_length=50)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_response', models.JSONField(default=dict)),
                ('webhook_received', models.BooleanField(default=False)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Test notes for debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_test_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment.captured', 'Payment Captured'), ('payment.failed', 'Payment Failed'), ('payment.authorized', 'Payment Authorized'), ('refund.created', 'Refund Created'), ('settlement.processed', 'Settlement Processed'), ('unknown', 'Unknown Event')], db_index=True, max_length=50)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('raw_body', models.JSONField(help_text='Raw webhook payload from Razorpay')),
                ('signature', models.CharField(blank=True, help_text='Webhook signature for verification', max_length=256)),
                ('signature_valid', models.BooleanField(default=False, help_text='Whether signature was valid')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('error', 'Error')], db_index=True, default='received', max_length=20)),
                ('response_message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at', 'event_type'], name='Hub_webhook_receive_79b84a_idx'), models.Index(fields=['payment_id', 'order_id'], name='Hub_webhook_payment_05d9c1_idx')],
            },
        ),
    ]
