# Generated by Django 5.2.9 on 2026-04-07 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0085_verificationtestlog_webhooklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upiverification',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='upiverification',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='upiverification',
            name='refund_attempted',
        ),
        migrations.AddField(
            model_name='upiverification',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes on this verification'),
        ),
        migrations.AddField(
            model_name='upiverification',
            name='return_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upi_verifications', to='Hub.returnrequest'),
        ),
        migrations.AddField(
            model_name='upiverification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upi_verifications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upiverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ADMIN_REVIEW', 'Pending Admin Review'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='upiverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upi_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
