# Generated by Django 5.2.9 on 2026-04-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0086_upi_verification_admin_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Show this reel in the homepage carousel'),
        ),
    ]
