# Generated by Django 5.2.9 on 2026-04-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0087_add_show_on_homepage_to_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
