# Generated by Django 5.2.9 on 2026-04-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0088_newslettersubscription_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_role',
            field=models.CharField(
                choices=[
                    ('gallery', 'Gallery Image'),
                    ('main', 'Main Product Image'),
                    ('description', 'Description Image'),
                ],
                default='gallery',
                help_text='How this image should be used for the product',
                max_length=20,
            ),
        ),
    ]
