# Generated by Django 5.2.9 on 2026-04-29 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0089_productimage_image_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product', 'size', 'color')},
        ),
    ]
