# Generated by Django 5.2.9 on 2026-05-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0090_alter_cart_unique_together_cart_color_cart_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button2_text',
            field=models.CharField(blank=True, default='', help_text="Second button text e.g. 'Read Editorial'", max_length=50),
        ),
        migrations.AddField(
            model_name='slider',
            name='button2_url',
            field=models.CharField(blank=True, default='', help_text='Second button URL', max_length=200),
        ),
        migrations.AddField(
            model_name='slider',
            name='eyebrow_text',
            field=models.CharField(blank=True, default='', help_text="Small text above title e.g. 'AUTUMN / WINTER 24'", max_length=100),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_italic_part',
            field=models.CharField(blank=True, default='', help_text='Italic part of the title (appended after title)', max_length=200),
        ),
        migrations.AddField(
            model_name='slider',
            name='use_as_hero',
            field=models.BooleanField(default=False, help_text='Show this slide in the desktop hero carousel'),
        ),
    ]
