# Generated by Django 5.0.7 on 2026-06-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0091_add_hero_fields_to_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('MANUAL', 'Manual Code'), ('NEW_CUSTOMER', 'New Customer'), ('FIRST_ORDER', 'First Order (5%)'), ('FREE_SHIPPING', 'Free Shipping'), ('SPEND_5K', 'Spend 5000 (5%)')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount'), ('FREE_SHIPPING', 'Free Shipping')], max_length=20),
        ),
    ]
