# Generated by Django 5.0.7 on 2026-06-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0093_seed_launch_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, default='', help_text='Email address used for order notifications', max_length=254),
        ),
    ]
