# Generated by Django 5.0.7 on 2026-06-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0094_order_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='featured_story_cta_text',
            field=models.CharField(blank=True, default='Watch the full series', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_story_cta_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_story_description',
            field=models.TextField(blank=True, default='Immerse yourself in our latest lookbook film, where fashion meets cinema. Explore the textures and flow of the new collection in motion.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_story_eyebrow',
            field=models.CharField(blank=True, default='Editorial Video', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_story_image',
            field=models.ImageField(blank=True, help_text='Featured section poster/image (recommended: 1200x900 or 4:3)', null=True, upload_to='site/featured_story/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_story_title',
            field=models.CharField(blank=True, default='The Art of Movement', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_story_video',
            field=models.FileField(blank=True, help_text='Featured section video (MP4 recommended)', null=True, upload_to='site/featured_story/'),
        ),
    ]
