# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0095_sitesettings_featured_story_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='benefit_1_text',
            field=models.CharField(blank=True, default='', help_text="First benefit text e.g. 'Premium Quality'", max_length=80),
        ),
        migrations.AddField(
            model_name='slider',
            name='benefit_2_text',
            field=models.CharField(blank=True, default='', help_text="Second benefit text e.g. 'Fast & Reliable Delivery'", max_length=80),
        ),
        migrations.AddField(
            model_name='slider',
            name='benefit_3_text',
            field=models.CharField(blank=True, default='', help_text="Third benefit text e.g. 'Easy Returns'", max_length=80),
        ),
        migrations.AddField(
            model_name='slider',
            name='offer_eyebrow',
            field=models.CharField(blank=True, default='', help_text="Offer badge top text e.g. 'UPTO'", max_length=50),
        ),
        migrations.AddField(
            model_name='slider',
            name='offer_footer_text',
            field=models.CharField(blank=True, default='', help_text="Offer badge footer text e.g. '+ EXTRA 10% CASHBACK'", max_length=120),
        ),
        migrations.AddField(
            model_name='slider',
            name='offer_main_text',
            field=models.CharField(blank=True, default='', help_text="Offer badge main text e.g. '50%'", max_length=40),
        ),
        migrations.AddField(
            model_name='slider',
            name='offer_subtext',
            field=models.CharField(blank=True, default='', help_text="Offer badge middle text e.g. 'OFF'", max_length=50),
        ),
    ]
