# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0115_slider_hero_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryicon',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text="Short homepage card description (e.g., 'Curated styles for every occasion')", max_length=140),
        ),
    ]
