# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0116_categoryicon_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryicon',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Homepage Shop By Category card image (recommended: 800x1000 or 4:5 ratio)', null=True, upload_to='category_cards/'),
        ),
    ]
