# Generated by Django 4.2.7 on 2026-07-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0117_alter_categoryicon_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment'), ('UPI', 'UPI'), ('CARD', 'Credit/Debit Card'), ('WALLET', 'VibeMall Wallet')], default='COD', max_length=20),
        ),
    ]
