# Generated by Django 4.2.7 on 2026-07-14 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hub', '0119_seller_access_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityrole',
            name='role_type',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('STAFF', 'Staff Member'), ('SELLER', 'Seller'), ('VIEWER', 'View Only'), ('CUSTOMER_SERVICE', 'Customer Service'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('SALES_MANAGER', 'Sales Manager'), ('MARKETING_MANAGER', 'Marketing Manager'), ('FINANCE_MANAGER', 'Finance Manager'), ('CUSTOM', 'Custom Role')], max_length=30),
        ),
        migrations.CreateModel(
            name='SellerAccessInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_access_invites_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_access_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
