# Generated by Django 4.2.7 on 2026-07-28 15:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hub', '0120_alter_securityrole_role_type_selleraccessinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerprofile',
            name='seller_available_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Confirmed seller earnings not yet paid out', max_digits=12),
        ),
        migrations.AddField(
            model_name='resellerprofile',
            name='seller_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Platform commission % on this seller's own product sales", max_digits=5),
        ),
        migrations.AddField(
            model_name='resellerprofile',
            name='seller_total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Lifetime net earnings from this user's own product sales", max_digits=12),
        ),
        migrations.AddField(
            model_name='resellerprofile',
            name='seller_total_orders',
            field=models.PositiveIntegerField(default=0, help_text="Number of orders containing this user's own products"),
        ),
        migrations.CreateModel(
            name='SellerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_seller_payouts', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Payout',
                'verbose_name_plural': 'Seller Payouts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text="Sum of base_price x quantity for this seller's items in the order", max_digits=12)),
                ('commission_percent', models.DecimalField(decimal_places=2, help_text='Commission rate snapshot at earning time; later rate changes never rewrite history', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax deducted at source, if applicable. Reserved; no deduction logic yet.', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='gross_amount - commission_amount - tds_amount; what the seller is owed', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('item_count', models.PositiveIntegerField(default=0, help_text='Units sold by this seller in the order')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_earnings', to='Hub.order')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='Hub.sellerpayout')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Earning',
                'verbose_name_plural': 'Seller Earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sellerpayout',
            index=models.Index(fields=['seller', 'status'], name='Hub_sellerp_seller__643d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerpayout',
            index=models.Index(fields=['status'], name='Hub_sellerp_status_bcb471_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerearning',
            index=models.Index(fields=['seller', 'status'], name='Hub_sellere_seller__e5d8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerearning',
            index=models.Index(fields=['status'], name='Hub_sellere_status_e7dac3_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerearning',
            constraint=models.UniqueConstraint(fields=('order', 'seller'), name='uniq_seller_earning_per_order'),
        ),
    ]
