# Generated by Django 4.2.7 on 2026-07-29 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hub', '0121_resellerprofile_seller_available_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPromptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False, help_text='True once the shopper reviewed or dismissed it, rather than just seeing it.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_prompts', to='Hub.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shown_at'],
                'indexes': [models.Index(fields=['user', 'shown_at'], name='Hub_reviewp_user_id_041b18_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reviewpromptlog',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='uniq_review_prompt_per_user_product'),
        ),
    ]
