# Generated by Django 4.2.7 on 2026-07-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0122_reviewpromptlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='One checkout session; prevents duplicate orders.', max_length=64, null=True, unique=True),
        ),
    ]
