# Generated by Django 5.2.9 on 2026-07-30 08:18

import Hub.models_product_automation
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0123_order_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=uuid.uuid4, editable=False, help_text='Stable identifier used for media paths and log correlation', max_length=36, unique=True)),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('csv', 'CSV Import'), ('excel', 'Excel Import'), ('api', 'Supplier API')], default='telegram', max_length=20)),
                ('source_chat_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_message_id', models.CharField(blank=True, default='', help_text='Provider message id — makes re-delivery idempotent', max_length=100)),
                ('source_group_id', models.CharField(blank=True, db_index=True, default='', help_text='Telegram media_group_id: album parts share one draft', max_length=100)),
                ('source_author', models.CharField(blank=True, default='', max_length=150)),
                ('raw_text', models.TextField(blank=True, default='', help_text='Supplier message exactly as received')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Full provider payload for replay/debugging')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('PENDING', 'Pending Approval'), ('DUPLICATE', 'Possible Duplicate'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='RECEIVED', max_length=20)),
                ('parsed', models.JSONField(blank=True, default=dict, help_text='Structured attributes extracted from the message (see automation.ai.schema)')),
                ('ai_suggestions', models.JSONField(blank=True, default=dict, help_text='Suggested category/sub-category with confidence and reasoning')),
                ('ai_model', models.CharField(blank=True, default='', max_length=80)),
                ('ai_tokens_used', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, default='', help_text='Chosen by the admin at approval time', max_length=50)),
                ('sub_category', models.CharField(blank=True, default='', max_length=100)),
                ('duplicate_reasons', models.JSONField(blank=True, default=list)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('events', models.JSONField(blank=True, default=list, help_text='Append-only processing audit trail')),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Bumped as album parts arrive; parsing waits for this to settle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='Existing product this draft appears to duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_drafts', to='Hub.product')),
                ('published_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_drafts', to='Hub.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_product_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Draft',
                'verbose_name_plural': 'Product Drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDraftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Hub.models_product_automation.draft_image_upload_to)),
                ('role', models.CharField(choices=[('main', 'Main Product Image'), ('gallery', 'Gallery Image'), ('description', 'Description Image')], default='gallery', max_length=20)),
                ('color', models.CharField(blank=True, default='', help_text='Detected colour variant', max_length=100)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('phash', models.CharField(blank=True, db_index=True, default='', help_text='Perceptual hash — used for near-duplicate detection', max_length=64)),
                ('source_file_id', models.CharField(blank=True, default='', max_length=200)),
                ('analysis', models.JSONField(blank=True, default=dict, help_text='Raw vision output for this image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Hub.productdraft')),
            ],
            options={
                'verbose_name': 'Product Draft Image',
                'verbose_name_plural': 'Product Draft Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productdraft',
            index=models.Index(fields=['status', 'next_attempt_at'], name='Hub_product_status_9b24fd_idx'),
        ),
        migrations.AddIndex(
            model_name='productdraft',
            index=models.Index(fields=['source', 'source_group_id'], name='Hub_product_source_fd1140_idx'),
        ),
        migrations.AddConstraint(
            model_name='productdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('source_message_id', ''), _negated=True), fields=('source', 'source_message_id'), name='uniq_draft_per_source_message'),
        ),
        migrations.AddIndex(
            model_name='productdraftimage',
            index=models.Index(fields=['draft', 'role'], name='Hub_product_draft_i_099470_idx'),
        ),
    ]
