# Generated by Django 5.2.9 on 2026-07-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0124_productdraft_productdraftimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdraftimage',
            name='crop_bottom_px',
            field=models.PositiveIntegerField(default=0, help_text='Pixels trimmed from the bottom when published (0 = no crop)'),
        ),
        migrations.AddField(
            model_name='productdraftimage',
            name='suggested_crop_bottom_px',
            field=models.PositiveIntegerField(default=0, help_text='Auto-detected height of the supplier code strip'),
        ),
    ]
