# Generated by Django 5.2.9 on 2026-07-30 11:26

import Hub.models_product_automation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0125_productdraftimage_crop_bottom_px_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDraftVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=Hub.models_product_automation.draft_video_upload_to)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=Hub.models_product_automation.draft_thumbnail_upload_to)),
                ('title', models.CharField(blank=True, default='', help_text='Reel title; falls back to the product name on approval', max_length=200)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Seconds, as reported by Telegram')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('create_reel', models.BooleanField(default=True, help_text='Create a Reel for this video when the product is approved')),
                ('publish_reel', models.BooleanField(default=False, help_text='Publish the Reel immediately (otherwise it is created unpublished)')),
                ('source_file_id', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Hub.productdraft')),
            ],
            options={
                'verbose_name': 'Product Draft Video',
                'verbose_name_plural': 'Product Draft Videos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
