# Generated by Django 4.2.7 on 2026-07-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0126_productdraftvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdraft',
            name='intake_closed',
            field=models.BooleanField(default=False, help_text='Set once the description has arrived for photos already staged. Suppliers send photos, then the description, then the next product — so a closed draft is a finished item and the next message starts a new one.'),
        ),
    ]
