# Generated by Django 4.2.7 on 2026-07-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0127_draft_intake_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdraft',
            name='awaiting_rate',
            field=models.BooleanField(default=False, help_text='The description arrived for photos already staged, so the only message that may still join is the rate. Distinct from a draft whose description came first — there, photos are still arriving.'),
        ),
        migrations.AddField(
            model_name='productdraft',
            name='follow_up_price',
            field=models.CharField(blank=True, default='', help_text='Price sent as its own message after the description, kept apart from the prices inside the catalogue text because it means something different: it is the rate this shop pays.', max_length=20),
        ),
        migrations.AlterField(
            model_name='productdraft',
            name='intake_closed',
            field=models.BooleanField(default=False, help_text='Set once nothing further can join this draft. Suppliers send photos, then the description, then sometimes the rate as its own message — so the draft stays open for a short window after the description in case that price is still coming.'),
        ),
    ]
