# Generated by Django 4.2.7 on 2026-08-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0128_draft_rate_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_provider_override',
            field=models.CharField(blank=True, default='', help_text='Overrides AUTOMATION_AI_PROVIDER at runtime. Empty = use the .env default.', max_length=20),
        ),
    ]
