# Generated by Django 5.2.9 on 2026-08-06 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0129_sitesettings_ai_provider_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('theme_name', models.CharField(blank=True, max_length=50)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.CharField(blank=True, help_text='Comma-separated, without #', max_length=500)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('ai_provider', models.CharField(blank=True, help_text='Which AI provider wrote the copy, if any', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('telegram_message_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_assets', to='Hub.product')),
                ('regenerated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerations', to='Hub.creativeasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
